stages:
  - test
  - build
  - docker

job_test:
  stage: test
  image: alpine:latest
  script:
    - echo "Les tests passent avec succes !"

job_build:
  stage: build
  image: alpine:latest
  script:
    - echo "Le build est un succes !"

job_docker:
  stage: docker
  image: alpine:latest
  script:
    - echo "L'image Docker a bien ete simulee !"