apiVersion: v1
kind: Namespace
metadata:
  name: devops-l3gl
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-l3gl
type: Opaque
data:
  # Le mot de passe 'root' encode en base64
  mysql-root-password: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-l3gl
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: devops_l3gl
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devops-l3gl
spec:
  ports:
    - port: 3306
  selector:
    app: mysql